name: apiserver
version: 0.0.1



config:

    logfile: './main.log'
    pidfile: './main.pid'


    default:

        port: 8000

        db:
            host: 176.31.14.255
            port: 3306

            timezone: Z

        payment:
            'robokassa':
                merchantUrl: http://test.robokassa.ru/Index.aspx # merchantUrl: https://auth.robokassa.ru/Merchant/Index.aspx
                merchant: tehfreak
                pass1: b9f1c6834f49a8e8
                pass2: f4f397e82f26bd34
                resultUrl: http://play.local.awesome39.com:8000/payment/robokassa/result
                successUrl: http://play.local.awesome39.com:8000/payment/robokassa/success

    development:

        installed: false

        host: local.awesome39.com

        db:
            database: apiserver

            user: apiserver
            password: iamthe1337

            debug: true

        payment:
            'robokassa':
                merchantUrl: http://play.local.awesome39.com:8000/payment/robokassa/debug

    production:

        installed: true

        host: flydev.awesome39.com

        db: # http://red.flydev.net/issues/5#note-3
            database: apiserver

            user: apiserver
            password: iamthe1337

            debug: false



scripts:
    start: node node.js



dependencies:

    async: 0.2.9
    extend: 1.1.3

    express: 3.3.7

    passport: 0.1.17

    connect-redis: 1.4.5
    redis: 0.8.4
    mysql: 2.0.0-alpha8

    log: 1.4.0
    request: 2.27.0
    deferred: 0.6.5
    qs: 0.6.5
    cookie-jar: 0.3.0
    oauth-sign: 0.3.0

engines:
    node: 0.10.17

